FROM apache/airflow:2.9.1

USER root

RUN apt-get update && \
    apt-get install -y curl unzip && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-docker \
    docker